### ISSUE TITLE
Counter forward stops at 60 seconds

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/SimpleTimerAddon#36]
In [the demo](https://addonsv24.flowingcode.com/simple-timer/simple-timer) if you start the counter so it goes forward (Count up checkbox) it stops at 60 seconds.

**Comment by paodb** [comment]
The "problem" is here https://github.com/FlowingCode/SimpleTimerAddon/blob/9a71b928de47aa6d6127fa04a5f47872698a6920/src/main/resources/META-INF/frontend/simple-timer/simple-timer.js#L156 The calculations to know when to stop the counter are using the startTime. This property has a default value of 60. So, if you don't define a startTime (in this case it will be considered as a end-time) then it will stop at 60 seconds. 

Should the default value for the startTime property be set to some other default when countUp is set?

**Comment by javier-godoy** [comment]
As a user, I would expect that the default value of "startTime" does not affect when the count up ends, and if there is no "endTime", I would expect that the count up does never end. (It does not matter how it is implemented. Having "startTime" act as "endTime", and having that end-time be 60 just because 60 is a reasonable default for count down, is poor API and does not make sense)

**Comment by paodb** [comment]
The default value and the decrease logic are inherit from the original component that the add-on is based on. I would also expect that the count up never ends if no end time is defined. So how can we make the API less poor? Should we remove the default value in case on countUp or just replace the decrease logic or remove the default value completely from the component?

**Comment by mlopezFC** [comment]
At least the demo should make sense, when enabling the count up checkbox the textfield changes to "End time", we could populate it with 60.

![image](https://github.com/FlowingCode/SimpleTimerAddon/assets/28312758/230437b8-6d05-4e7d-af75-d8da713302f4)

**Comment by javier-godoy** [comment]
> The default value and the decrease logic are inherit from the original component that the add-on is based on. I would also expect that the count up never ends if no end time is defined. So how can we make the API less poor? Should we remove the default value in case on countUp or just replace the decrease logic or remove the default value completely from the component?

Any fix would be a breaking change, so let's figure out what makes most sense in this case.

IMHO either there should be no default value (_some_ initial value is needed for count down, but there's nothing special in "60" and users will likely need to set an initial value that is different from 60), **and/or** there should be an endTime property that applies to count up, so that count up does not _end_ at the so-called "startTime"
