### ISSUE TITLE
Continues requests when timer is running

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/SimpleTimerAddon#4]
When the timer is running there are continuous requests sent to the server, a better way of dealing with this is needed.

**Comment by javier-godoy** [comment]
This happens because `currentTime` is synchronized and `current-time-changed` fires on each animation frame: 
https://github.com/FlowingCode/SimpleTimerAddon/blob/29689b93df4f895acb38f0d02a66919e4d3ccfa3/src/main/java/com/flowingcode/vaadin/addons/simpletimer/SimpleTimer.java#L145-L148

`getCurrentTime` should be asynchronous, or at least updated on a debounced event instead of `@Synchronized`

**Comment by mlopezFC** [comment]
Based on that, I'm thinking about two approaches that could be implemented:

- Possibility of configuring how often the "current-time-changed" event can be fired from client side (ie: every 1 second, 5 seconds, etc.)
- Adding a new method that will function asynchronously (ie: receiving a lambda, etc.)

Maybe it would be nice to have the possibility of disabling the listening of the events would be nice (ie: if I want to obtain current time asynchronously I would prefer not to receive requests for synchronizing the current time)
